# Explora aquí

Se recomienda utilizar este cuaderno con fines de exploración.

Por ejemplo:

1. Puede importar el CSV generado por Python a su computadora portátil y explorarlo.
2. Puede conectarse a su base de datos usando `pandas.read_sql` desde este cuaderno y explorarla.

In [4]:
# Ejemplo de lectura de la base de datos SQL desde aquí
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
import pandas as pd

# cargar las variables del archivo .env
file_path = r"C:\Users\angel\connecting-to-a-sql-database-project-tutorial"
load_dotenv(dotenv_path=rf"{file_path}\.env.example")

connection_string = f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}"
engine = create_engine(connection_string).execution_options(autocommit=True)
engine.connect()

dataframe = pd.read_sql("Select * from books;", engine)

,book_id,title,total_pages,rating,isbn,published_date,publisher_id
0,1,Lean Software Development: An Agile Toolkit,240,4.17,9780320000000,2003-05-18,5
1,2,Facing the Intelligence Explosion,91,3.87,None,2013-02-01,7
2,3,Scala in Action,419,3.74,9781940000000,2013-04-10,1
3,4,Patterns of Software: Tales from the Software ...,256,3.84,9780200000000,1996-08-15,1
4,5,Anatomy Of LISP,446,4.43,9780070000000,1978-01-01,3
5,6,Computing machinery and intelligence,24,4.17,None,2009-03-22,4
6,7,XML: Visual QuickStart Guide,269,3.66,9780320000000,2009-01-01,5
7,8,SQL Cookbook,595,3.95,9780600000000,2005-12-01,7
8,9,The Apollo Guidance Computer: Architecture And...,439,4.29,9781440000000,2010-07-01,6
9,10,Minds and Computers: An Introduction to the Ph...,222,3.54,9780750000000,2007-02-13,7